# .github/workflows/deploy.yml
name: Deploy web/ to GitHub Pages

on:
  push:
    branches: [main] # 任意のデプロイトリガーに変更可

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy web/ to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
